#pragma once

#include "../utils/defs.hpp"


constexpr u32 SCREEN_HEIGHT_PX = 800;
constexpr u32 SCREEN_WIDTH_PX = SCREEN_HEIGHT_PX * 10 / 8;


constexpr u32 TILE_WIDTH_PX = 64;
constexpr u32 TILE_HEIGHT_PX = TILE_WIDTH_PX;

constexpr u32 PLAYER_WIDTH_PX = 12;
constexpr u32 PLAYER_HEIGHT_PX = PLAYER_WIDTH_PX;

constexpr u32 BLUE_WIDTH_PX = 5;
constexpr u32 BLUE_HEIGHT_PX = BLUE_WIDTH_PX;

constexpr u32 WALL_WIDTH_PX = 20;
constexpr u32 WALL_HEIGHT_PX = WALL_WIDTH_PX;


constexpr r32 TILE_LENGTH_M = 0.5f;

constexpr u32 MIN_SCREEN_WIDTH_TILE = 10;
constexpr u32 MAX_SCREEN_WIDTH_TILE = 100;

constexpr u32 WORLD_WIDTH_TILE = 50;
constexpr u32 WORLD_HEIGHT_TILE = 25;
constexpr u32 N_WORLD_TILES = WORLD_WIDTH_TILE * WORLD_HEIGHT_TILE;

constexpr r32 MIN_SCREEN_WIDTH_M = MIN_SCREEN_WIDTH_TILE * TILE_LENGTH_M;
constexpr r32 MAX_SCREEN_WIDTH_M = MAX_SCREEN_WIDTH_TILE * TILE_LENGTH_M;

constexpr u32 N_WALL_ENTITIES = 2 * WORLD_WIDTH_TILE + 2 * WORLD_HEIGHT_TILE - 4;

constexpr u32 N_BLUE_W = WORLD_WIDTH_TILE - 8;
constexpr u32 N_BLUE_H = WORLD_HEIGHT_TILE - 4;
constexpr u32 N_BLUE_ENTITIES = N_BLUE_W * N_BLUE_H;

constexpr u32 N_PLAYER_ENTITIES = 1;

constexpr u32 N_ENTITIES = N_BLUE_ENTITIES + N_WALL_ENTITIES + N_PLAYER_ENTITIES;
constexpr u32 N_MOVABLE_ENTITIES = N_PLAYER_ENTITIES + N_BLUE_ENTITIES;


constexpr auto PLAYER_BEGIN = 0U;
constexpr auto PLAYER_END = N_PLAYER_ENTITIES;
constexpr auto BLUE_BEGIN = PLAYER_END;
constexpr auto BLUE_END = BLUE_BEGIN + N_BLUE_ENTITIES;
constexpr auto WALL_BEGIN = BLUE_END;
constexpr auto WALL_END = WALL_BEGIN + N_WALL_ENTITIES;